### ISSUE TITLE
How did you get the confusion matrix in your experiment?

### ISSUE THREAD

**Issue by tanaka-jp** [otiliastr/coarse-to-fine-curriculum#1]
Hello.
I like your paper in which the new idea of curriculum learning was proposed.

But I must ask you a question.

Which did you get the confusion matrix from, training data or test data?
I think that getting the confusion matrix from test data is a kind of data leakage.

**Comment by otiliastr** [comment]
Hello,

Thanks for your interest in the paper! :) 

The confusion matrix is actually computed on the validation data, which is a small proportion of the training data that we set aside. See [this line ](https://github.com/otiliastr/coarse-to-fine-curriculum/blob/00fe0ad58dd2a5871958307f7791d93003b6310b/src/learning/hierarchy_computation.py#L93) in the compute_confusion_matrix function.

**Comment by tanaka-jp** [comment]
Thanks for answering.
